const products = [
  {
    id: '1',
    name: 'single economy',
    price: 100,
    image: './images/details-1.jpeg',
    capacity: 1,
    size: 200,
    breakfast: false,
    pets: false,
  },
  {
    id: '2',
    name: 'single basic',
    price: 150,
    size: 250,
    capacity: 1,
    image: './images/details-2.jpeg',
    pets: false,
    breakfast: false,

  },
  {
    id: '3',
    name: 'single standard',
    price: 250,
    size: 300,
    capacity: 1,
    image: './images/details-3.jpeg',
    pets: true,
    breakfast: false,
  },
  {
    id: '4',
    name: 'single deluxe',
    price: 300,
    size: 400,
    capacity: 1,
    image: './images/details-4.jpeg',
    pets: true,
    breakfast: true,
  },
  {
    id: '5',
    name: 'double economy',
    price: 200,
    capacity: 2,
    size: 300,
    image: './images/room-2.jpeg',
    pets: false,
    breakfast: false,
  },
  {
    id: '6',
    name: 'double basic',
    price: 250,
    size: 350,
    capacity: 2,
    image: './images/room-3.jpeg',
    pets: false,
    breakfast: false,
  },
  {
    id: '7',
    name: 'double standard',
    price: 300,
    size: 400,
    capacity: 2,
    image: './images/room-4.jpeg',
    pets: true,
    breakfast: false,
  },
  {
    id: '8',
    name: 'double deluxe',
    price: 400,
    size: 500,
    capacity: 2,
    image: './images/room-5.jpeg',
    pets: true,
    breakfast: true,
  },
  {
    id: '9',
    name: 'family economy',
    price: 300,
    size: 500,
    capacity: 3,
    image: './images/room-6.jpeg',
    pets: false,
    breakfast: false,
  },
  {
    id: '10',
    name: 'family basic',
    price: 350,
    capacity: 4,
    size: 550,
    image: './images/room-7.jpeg',
    pets: false,
    breakfast: false,
  },
  {
    id: '11',
    name: 'family standard',
    price: 400,
    image: './images/room-8.jpeg',
    pets: true,
    size: 600,
    capacity: 5,
    breakfast: false,
  },
  {
    id: '12',
    name: 'family deluxe',
    price: 500,
    size: 700,
    image: './images/room-9.jpeg',
    pets: true,
    capacity: 6,
    breakfast: true,
  },
  {
    id: '13',
    name: 'presidential',
    price: 600,
    size: 1000,
    capacity: 10, 
    image: './images/room-10.jpeg',
    pets: true,
    breakfast: true,
  },
]
export default products
